[package]
name = "chess_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
crossterm = "0.23"

# for speed testing
[profile.test]
opt-level = 3

[profile.release.build-override]
opt-level = 3