[package]
name = "chess_rs"
version = "0.1.0"
edition = "2021"


[dependencies]
winit = "0.26"
pixels = "0.9.0"
winit_input_helper = "0.12"
env_logger = "0.9"
log = "0.4.17"

[profile.test]
opt-level = 3

[profile.release.build-override]
opt-level = 3