[package]
name = "chess_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.23"

[profile.test]
opt-level = 3

[profile.dev]
opt-level = 3

[profile.release.build-override]
opt-level = 3